#!/bin/bash -l
#PBS -N compute_glm
#PBS -l nodes=1:ppn=8
#PBS -l walltime=20:00:00
#PBS -M ali39@jhu.edu
#PBS -m abe
#PBS -q dque
#PBS -S /bin/bash
#PBS -d /home/ali/motorControl-InputOutputModels/server
#PBS -e /home/ali/motorControl-InputOutputModels/server/_log/test.err
#PBS -o /home/ali/motorControl-InputOutputModels/server/_log/test.out
cd /home/ali/motorControl-InputOutputModels/server

proc=0 
pbsdsh -n $proc /home/ali/motorControl-InputOutputModels/server/runglm.sh $index &
wait